Test 72 As a user I should be able to login with my Google account
kristiyanplpeev/vacations pull request #1
Opened 2021-07-21 12:32 UTC by kristiyanplpeev

Front end - Login page & Header, in login page there is a Login with google button. The header shows user names and profile pic.

Back-end - implemented login with google & JWT.

2021-07-22 14:27 UTC, MilenIvanovv requested changes
I think the code looks great. Left some comments where it can be improved.

2021-07-22 14:27 UTC, MilenIvanovv commented on client/src/components/Header/Header.tsx
> +    if (this.props.userStatus !== this.state.isUserLogged) {
I think there is mo suitable name for **userStatus** prop (or redux state). Its type is a boolean so **isUserLogged** is ok. By status, I refer to something that fixed number of custom values like enums ( `Enum { loggedIn, notLoggedIn }`)

2021-07-22 14:27 UTC, MilenIvanovv commented on client/src/components/Header/Header.tsx
> +  state = {
Is there a way not to use component state here?

2021-07-22 14:27 UTC, MilenIvanovv commented on client/src/components/Login/Login.css
> +  background-color: rgb(220, 0, 78) !important;
We should avoid using !important.

2021-07-22 14:27 UTC, MilenIvanovv commented on client/src/components/Login/Login.tsx
> +          onClick={() => window.location.assign("http://localhost:5000/auth/google")}
You can reuse **BASE_URL** constant here.

2021-07-22 14:27 UTC, MilenIvanovv commented on client/src/components/Login/Redirecting.tsx
> +  state = {
Should be in constructor above componentDidMount

2021-07-22 14:27 UTC, MilenIvanovv commented on client/src/components/Login/Redirecting.tsx
> +      const res = await fetch(`${BASE_URL}auth/users`, {
This logic for making requests to the server can be extracted in a service. One benefit of this is that it will make it reusable. 
Also in our project and I think most people import libraries for making requests like Axios. You can consider using one.

2021-07-23 08:20 UTC, kristiyanplpeev commented on client/src/components/Header/Header.css
> +.header-menubutton{
done.

2021-07-23 08:37 UTC, kristiyanplpeev commented on README.md
> +        GOOGLE_CLIENT_ID=57121685326-pegp31vlg3n02i5hl57qdpqagekcsfdb.apps.googleusercontent.com
done.

2021-07-23 08:48 UTC, kristiyanplpeev commented on client/src/components/Header/Header.tsx
> +  state = {
done.

2021-07-23 08:49 UTC, kristiyanplpeev commented on client/src/components/Header/Header.tsx
> +    this.setUserStatus();
done.

2021-07-23 09:10 UTC, kristiyanplpeev commented on client/src/components/Login/Redirecting.tsx
> +  state = {
done.

2021-07-23 12:40 UTC, kristiyanplpeev commented on client/src/components/Login/Login.tsx
> +          onClick={() => window.location.assign("http://localhost:5000/auth/google")}
done.

2021-07-23 13:19 UTC, kristiyanplpeev commented on client/src/components/Login/Login.css
> +  background-color: rgb(220, 0, 78) !important;
done.

2021-07-26 05:57 UTC, kristiyanplpeev commented on client/src/components/Header/Header.tsx
> +    if (this.props.userStatus !== this.state.isUserLogged) {
done.

2021-07-26 05:58 UTC, kristiyanplpeev commented on client/src/components/Login/Redirecting.tsx
> +      const res = await fetch(`${BASE_URL}auth/users`, {
done.

2021-07-26 12:35 UTC, MilenIvanovv requested changes

2021-07-26 12:35 UTC, MilenIvanovv commented on server/src/google/utils/Serializer.ts
> +import { User } from '/home/kristiyan/Repos/vacations/server/src//model/user.entity';
If it works on your machine it doesn't mean it will work on mine :smile:

2021-07-27 06:18 UTC, kristiyanplpeev commented on server/src/google/utils/Serializer.ts
> +import { User } from '/home/kristiyan/Repos/vacations/server/src//model/user.entity';
done.

2021-07-29 06:56 UTC, MilenIvanovv approved these changes
LGTM, great job!

2021-07-29 16:03 UTC, merged