Test 95
kristiyanplpeev/vacations pull request #10
Opened 2021-09-10 08:07 UTC by kristiyanplpeev

Front end added select buttons for selecting which team and position i want to be displayed, also changed a bit service method for getting all users.

Back end changed method for getting users by adding filtering functionality.

2021-09-13 12:35 UTC, MilenIvanovv commented on client/src/components/UsersList/UsersList.tsx
> +  renderUsers(): Array<JSX.Element> | JSX.Element {
Omit Array<JSX.Element> |
Make it to return 
(
    <>
    this.state.users...
    </>
)

2021-09-13 12:38 UTC, MilenIvanovv commented on client/src/services/UserService.ts
> +    return (await axios.get(`${BASE_URL}users?teamId=${teamId}&positionId=${positionId}`, { headers: this.headers }))
Ussualy when there is a query param for filtering, like here, they are optional. When you don't provide them the request should return every user.

2021-09-13 12:40 UTC, MilenIvanovv commented on server/src/users/users.controller.ts
> +    @Query('positionId') positionId: string,
If choose leave the query params required, it is a good practice to check if they are undefined and throw badrequest

2021-09-13 12:47 UTC, MilenIvanovv commented
LGTM, left some comments for minor changes

2021-09-13 12:48 UTC, MilenIvanovv requested changes
LGTM, left some comments for minor changes

2021-09-14 13:11 UTC, kristiyanplpeev commented on client/src/components/UsersList/UsersList.tsx
> +  renderUsers(): Array<JSX.Element> | JSX.Element {
done.

2021-09-14 14:33 UTC, kristiyanplpeev commented on client/src/services/UserService.ts
> +    return (await axios.get(`${BASE_URL}users?teamId=${teamId}&positionId=${positionId}`, { headers: this.headers }))
done.

2021-09-14 14:33 UTC, kristiyanplpeev commented on server/src/users/users.controller.ts
> +    @Query('positionId') positionId: string,
done.

2021-09-14 14:37 UTC, MilenIvanovv approved these changes

2021-09-14 14:44 UTC, merged