Test 75 As a logged user I should be able to add new PTO
kristiyanplpeev/vacations pull request #2
Opened 2021-08-05 08:26 UTC by kristiyanplpeev

Front end - added new PTO page with form for PTO details and table with PTO summary.

Back end - added holiday controller and service, and new tables about PTOs into the database.

2021-08-06 14:10 UTC, MilenIvanovv requested changes
I think the code looks great. There are small things that can improve readability. Left some comments. 

Usually, the union type is not a good indicator. Try to avoid it.

2021-08-06 14:10 UTC, MilenIvanovv commented on client/src/components/NewPTO/AdditionalInfo/AdditionalInfo.tsx
> +      const approversArr = this.props.approvers.value
This logic can be extracted in a private function. The name of the function would save reading the code.

2021-08-06 14:10 UTC, MilenIvanovv commented on client/src/components/NewPTO/DatesCalculator/DatesCalculator.tsx
> +      const nonWorkingDays = this.props.holidayDaysStatus
This can be extracted in a function. It will make the **componentDidUpdate** method more readable.

2021-08-06 14:10 UTC, MilenIvanovv commented on client/src/components/NewPTO/DatesCalculator/DatesCalculator.tsx
> +                        onClose={() => this.handlePopoverClose()}
Here you can directly pass the handler by reference.
onClose={this.handlePopoverClose}

2021-08-06 14:10 UTC, MilenIvanovv commented on client/src/components/NewPTO/DatesCalculator/DatesCalculator.tsx
> +                        <Typography style={{ whiteSpace: "pre-wrap" }}>{this.state.freeDaysStatuses}</Typography>
It is not a big deal but inline styles should be avoided

2021-08-09 05:09 UTC, kristiyanplpeev commented on client/src/common/AppError/AppError.css
> +.AppError {
done.

2021-08-09 05:16 UTC, kristiyanplpeev commented on client/src/common/types.ts
> +  startingDate: string;
done.

2021-08-09 06:45 UTC, kristiyanplpeev commented on client/jest.config.js
> +    //  "^.+\\.tsx?$": "ts-jest",
done.

2021-08-09 07:36 UTC, kristiyanplpeev commented on client/src/common/AppError/AppError.tsx
> +  message: string | boolean;
done.

2021-08-09 07:54 UTC, kristiyanplpeev commented on client/src/components/NewPTO/AdditionalInfo/AdditionalInfo.css
> +  width: 80%;
done.

2021-08-09 08:24 UTC, kristiyanplpeev commented on client/src/components/NewPTO/AdditionalInfo/AdditionalInfo.tsx
> +  warning: string | null;
done.

2021-08-09 08:28 UTC, kristiyanplpeev commented on client/src/components/NewPTO/AdditionalInfo/AdditionalInfo.tsx
> +                  onClick={() => this.addPTO()}
done.

2021-08-09 08:51 UTC, kristiyanplpeev commented on client/src/components/NewPTO/AdditionalInfo/AdditionalInfo.tsx
> +      const approversArr = this.props.approvers.value
done.

2021-08-09 09:15 UTC, kristiyanplpeev commented on client/src/components/NewPTO/DatesCalculator/DatesCalculator.tsx
> +      const nonWorkingDays = this.props.holidayDaysStatus
done.

2021-08-09 09:20 UTC, kristiyanplpeev commented on client/src/components/NewPTO/DatesCalculator/DatesCalculator.tsx
> +                        <Typography style={{ whiteSpace: "pre-wrap" }}>{this.state.freeDaysStatuses}</Typography>
done.

2021-08-09 09:21 UTC, kristiyanplpeev commented on client/src/components/NewPTO/DatesCalculator/DatesCalculator.tsx
> +                        onClose={() => this.handlePopoverClose()}
done.

2021-08-09 11:25 UTC, kristiyanplpeev commented on client/src/components/NewPTO/AdditionalInfo/AdditionalInfo.tsx
> +  setStartingDate: (date: MaterialUiPickersDate, value: string | null | undefined) => Promise<void>;
It is default materialUI type.

2021-08-09 11:26 UTC, kristiyanplpeev commented on client/src/components/NewPTO/AdditionalInfo/AdditionalInfo.spec.tsx
> +  it("Should render warning after clicking Add button with invalid PTO period", () => {
done.

2021-08-09 12:27 UTC, MilenIvanovv requested changes
Fron-end LGTM. Reviewed also the back-end. Left some comments. Main things I found:
- Use Array<T> instead of []. I think it is more readable
- Checking an object for 'message' property for error handling. It works fine but it is not clear to me. The exceptions can be utilized here.

2021-08-09 12:27 UTC, MilenIvanovv commented on client/src/components/NewPTO/DatesCalculator/DatesCalculator.tsx
> +  nonWorkingDays: string[];
In the constitution is said that we should use Array<> instead of []

2021-08-09 12:27 UTC, MilenIvanovv commented on server/src/holidays/dto/holidays.dto.ts
> +  // @IsDateString({}, { message: 'The submitted starting date is invalid.' })
Why is commented out?

2021-08-09 12:27 UTC, MilenIvanovv commented on server/src/holidays/holidays.controller.ts
> +    if ('message' in vacationDays) {
I think there is a better way. Try to throw an error in calculate day with try-catch block here.

2021-08-09 12:27 UTC, MilenIvanovv commented on server/src/holidays/holidays.controller.ts
> +    if ('message' in newHoliday) {
same as above

2021-08-09 12:27 UTC, MilenIvanovv commented on server/src/holidays/holidays.service.spec.ts
> +    find: jest.fn((something) => Promise.resolve(constantHolidays)),
You can omit the input (something) if it is not used

2021-08-09 12:27 UTC, MilenIvanovv commented on server/src/holidays/holidays.service.ts
> +  }[] => {
Use Array<T> instead of []

2021-08-09 12:27 UTC, MilenIvanovv commented on server/src/holidays/holidays.service.ts
> +    if (!Array.isArray(constantHolidays) && 'message' in constantHolidays) {
Why do we check for property **message** here?

2021-08-09 12:34 UTC, kristiyanplpeev commented on server/src/holidays/holidays.service.spec.ts
> +    find: jest.fn((something) => Promise.resolve(constantHolidays)),
done.

2021-08-09 12:40 UTC, kristiyanplpeev commented on client/src/components/NewPTO/AdditionalInfo/AdditionalInfo.tsx
> +                    onChange={(date: MaterialUiPickersDate, value: OptionalWithNull<string>) =>
done.

2021-08-09 12:41 UTC, kristiyanplpeev commented on client/src/components/NewPTO/DatesCalculator/DatesCalculator.tsx
> +  nonWorkingDays: string[];
done.

2021-08-09 12:46 UTC, kristiyanplpeev commented on server/src/holidays/dto/holidays.dto.ts
> +  // @IsDateString({}, { message: 'The submitted starting date is invalid.' })
done.

2021-08-09 12:48 UTC, kristiyanplpeev commented on server/src/holidays/holidays.service.ts
> +  }[] => {
done.

2021-08-09 13:30 UTC, kristiyanplpeev commented on server/src/holidays/holidays.controller.ts
> +    if ('message' in vacationDays) {
done.

2021-08-09 13:30 UTC, kristiyanplpeev commented on server/src/holidays/holidays.controller.ts
> +    if ('message' in newHoliday) {
done.

2021-08-09 13:30 UTC, kristiyanplpeev commented on server/src/holidays/holidays.service.ts
> +    if (!Array.isArray(constantHolidays) && 'message' in constantHolidays) {
done.

2021-08-10 07:38 UTC, MilenIvanovv approved these changes

2021-08-10 07:40 UTC, merged