Test 78 As a user I should be able to click and open the PTO in view only mode
kristiyanplpeev/vacations pull request #4
Opened 2021-08-11 10:09 UTC by kristiyanplpeev

Front end - added new page with PTO detailed view.

Back end - added endpoint for getting PTO full info by passing PTO id.

2021-08-11 10:34 UTC, MilenIvanovv requested changes
Looks great, i left some comments for minor changes

2021-08-11 10:34 UTC, MilenIvanovv commented on server/src/holidays/holidays.service.ts
> +    try {
There is no point of this try catch

2021-08-11 10:34 UTC, MilenIvanovv commented on server/src/holidays/holidays.service.ts
> +    try {
The same message will be thrown without it

2021-08-11 10:34 UTC, MilenIvanovv commented on client/src/inversify/interfaces.ts
>    userPTOsRequest(): Promise<UserHolidayType[]>;
This is not changed in this PR but the Array<> type can be used here.

2021-08-11 10:34 UTC, MilenIvanovv commented on client/src/inversify/interfaces.ts
>  export interface UserServiceInterface {
We use the Interface convention which has "I" at the start in the interface names.

2021-08-11 10:57 UTC, kristiyanplpeev commented on server/src/holidays/holidays.service.ts
> +    try {
done.

2021-08-11 11:19 UTC, kristiyanplpeev commented on client/src/inversify/interfaces.ts
>    userPTOsRequest(): Promise<UserHolidayType[]>;
done.

2021-08-11 11:20 UTC, kristiyanplpeev commented on client/src/inversify/interfaces.ts
>  export interface UserServiceInterface {
done.

2021-08-12 10:44 UTC, MilenIvanovv approved these changes
LGTM

2021-08-12 11:12 UTC, merged