Test 79 As a user I should be able to download generated PTO document
kristiyanplpeev/vacations pull request #5
Opened 2021-08-12 15:28 UTC by kristiyanplpeev

Front-end added functionality for generating and downloading a PDF file.

2021-08-12 15:33 UTC, MilenIvanovv requested changes
LGTM left one comment for a minor change

2021-08-12 15:33 UTC, MilenIvanovv commented on client/src/components/PTODetails/PTODetails.tsx
> +    return daysStatuses.filter((el) => el.status === "workday").length;
Use the status "working" from enum

2021-08-13 06:54 UTC, kristiyanplpeev commented on client/src/components/PTODetails/PTODetails.tsx
> +    return daysStatuses.filter((el) => el.status === "workday").length;
done.

2021-08-13 06:58 UTC, MilenIvanovv approved these changes
LGTM

2021-08-13 07:02 UTC, merged