Test 91 Project Refactoring
kristiyanplpeev/vacations pull request #6
Opened 2021-08-16 08:13 UTC by kristiyanplpeev

Front-end - added PTO service, fixed some naming issues, using interfaces instead of types.

Back-end added PTO service.

2021-08-16 08:55 UTC, MilenIvanovv requested changes
Great, I think a bit more changes are needed about the naming, but the code now is more readable.

2021-08-16 08:55 UTC, MilenIvanovv commented on client/.vscode/settings.json
> +    "cSpell.words": [
This .vscode is genereted by vs and saves your project specific vscode settings. This file should't be commited

2021-08-16 08:55 UTC, MilenIvanovv commented on client/src/common/types.ts
> +export interface IUserHolidayBasicInfo {
There are no other UserHoliday types so just IUserHoliday i think is a more suitable name.

2021-08-16 08:55 UTC, MilenIvanovv commented on client/src/common/types.ts
>  export type TextFieldType = {
No need of **type** at the end in the name

2021-08-16 08:55 UTC, MilenIvanovv commented on client/src/common/types.ts
> +export type IUserInfo = {
IUserInfo - Info does not give much information. Try to avoid it when naming.

2021-08-16 08:55 UTC, MilenIvanovv commented on client/src/common/types.ts
> +export interface IPTOFullInfo extends IUserHolidayBasicInfo {
If there is no other interface with partial info we don't need to say here it is full info.

2021-08-16 08:55 UTC, MilenIvanovv commented on client/src/components/Homepage/Homepage.tsx
> +    const userPTOs = await this.PTOService.userPTOs();
LGTM, however, is not clear what the method does. I would name it **.getUserPTOs()**, but now it is more readable than before.

2021-08-16 08:55 UTC, MilenIvanovv commented on client/src/services/PTOService.ts
> +    return (await axios.get(`${BASE_URL}holidays/users`, { headers })).data;
What happens if getting user PTOs returns an error?

2021-08-16 08:55 UTC, MilenIvanovv commented on server/src/holidays/holidays.service.ts
> +      const datesBetween = DateUtil.getDatesBetweenDates(holidayPeriodAsString);
Here i think **getPeriodBetweenDates** is more suitable name for the method.

2021-08-16 08:55 UTC, MilenIvanovv commented on server/src/holidays/holidays.service.ts
>        throw new Error(error.message);
What do you accomplish with this try-catch block?

2021-08-16 13:08 UTC, kristiyanplpeev commented on client/.vscode/settings.json
> +    "cSpell.words": [
done.

2021-08-16 13:16 UTC, kristiyanplpeev commented on client/src/common/types.ts
> +export interface IUserHolidayBasicInfo {
done.

2021-08-16 13:17 UTC, kristiyanplpeev commented on client/src/common/types.ts
>  export type TextFieldType = {
done.

2021-08-16 13:59 UTC, kristiyanplpeev commented on client/src/common/types.ts
> +export type IUserInfo = {
done.

2021-08-16 14:00 UTC, kristiyanplpeev commented on client/src/components/Homepage/Homepage.tsx
> +    const userPTOs = await this.PTOService.userPTOs();
done.

2021-08-16 14:02 UTC, kristiyanplpeev commented on server/src/holidays/holidays.service.ts
> +      const datesBetween = DateUtil.getDatesBetweenDates(holidayPeriodAsString);
done.

2021-08-16 14:18 UTC, kristiyanplpeev commented on client/src/common/types.ts
> +export interface IPTOFullInfo extends IUserHolidayBasicInfo {
done.

2021-08-17 11:59 UTC, kristiyanplpeev commented on server/src/holidays/holidays.service.ts
>        throw new Error(error.message);
done.

2021-08-19 07:29 UTC, kristiyanplpeev commented on client/src/services/PTOService.ts
> +    return (await axios.get(`${BASE_URL}holidays/users`, { headers })).data;
done.

2021-08-25 07:09 UTC, staev approved these changes

2021-08-31 10:50 UTC, MilenIvanovv approved these changes
LGTM

2021-08-31 10:55 UTC, merged