TEST 89 As a user I should be able to see list of all users
kristiyanplpeev/vacations pull request #8
Opened 2021-09-02 15:52 UTC by kristiyanplpeev

Backend - added new module users with endpoint for getting all users.

Frontend - added navigation at the top bar, admin home view, and view with all listed users.

2021-09-07 06:56 UTC, MilenIvanovv requested changes
LGTM, left some comments with a question and for minor changes

2021-09-07 06:56 UTC, MilenIvanovv commented on client/src/components/SideBar/SideBar.tsx
> +    if (!this.props.location.pathname.includes("/admin")) return <></>;
I think App.tsx is more suitable for this logic. Everything about url/paths is in there.

2021-09-07 06:56 UTC, MilenIvanovv commented on client/src/components/AdminUsers/AdminUsers.tsx
> +class AdminUsers extends Component<AdminUsersProps, AdminUserState> {
I think just Users or UsersList is a more suitable name for this component. I thought that AdminUsers renders only users that are with role admin.

2021-09-07 06:56 UTC, MilenIvanovv commented on server/src/users/users.controller.spec.ts
> +    expect(controller).toBeDefined();
What are the benefits of this test?

2021-09-07 06:56 UTC, MilenIvanovv commented on server/src/users/users.service.spec.ts
> +    expect(service).toBeDefined();
What are the benefits of this test?

2021-09-08 11:13 UTC, kristiyanplpeev commented on client/src/components/SideBar/SideBar.tsx
> +    if (!this.props.location.pathname.includes("/admin")) return <></>;
done.

2021-09-08 11:21 UTC, kristiyanplpeev commented on client/src/components/AdminUsers/AdminUsers.tsx
> +class AdminUsers extends Component<AdminUsersProps, AdminUserState> {
done.

2021-09-08 11:27 UTC, kristiyanplpeev commented on server/src/users/users.controller.spec.ts
> +    expect(controller).toBeDefined();
done.

2021-09-08 11:27 UTC, kristiyanplpeev commented on server/src/users/users.service.spec.ts
> +    expect(service).toBeDefined();
done.

2021-09-08 13:48 UTC, MilenIvanovv approved these changes
LGTM

2021-09-08 13:53 UTC, merged