Test 90 In usr list page I should be able to change in bulk users's posittion and team
kristiyanplpeev/vacations pull request #9
Opened 2021-09-08 15:58 UTC by kristiyanplpeev

Front end added new view for changing users team and position.

Back end added endpoints for getting teams, positions, user's team, user's position, and changint user's team and position.

2021-09-09 08:38 UTC, MilenIvanovv requested changes
Look great to me. I left some comments where it can be improved

2021-09-09 08:38 UTC, MilenIvanovv commented on client/src/services/UserService.ts
> +    const headers = {
There is a code duplication in the service. You can think of a way how we can avoid it.

2021-09-09 08:38 UTC, MilenIvanovv commented on server/src/users/users.service.spec.ts
> +  const mockedUserWithTeamAndPositionAsString = [
Those objects seem similar. Think of a way to remove the duplicated code

2021-09-09 08:38 UTC, MilenIvanovv commented on server/src/users/users.service.ts
> +      if (el.team === null) {
This is perfectly fine and readable. I would have done it like so:
`const team = el.team?.team ||  TeamsEnum.noTeam`

2021-09-09 09:55 UTC, kristiyanplpeev commented on client/src/services/UserService.ts
> +    const headers = {
done.

2021-09-09 10:15 UTC, kristiyanplpeev commented on server/src/users/users.service.spec.ts
> +  const mockedUserWithTeamAndPositionAsString = [
done.

2021-09-09 10:23 UTC, kristiyanplpeev commented on server/src/users/users.service.ts
> +      if (el.team === null) {
done.

2021-09-10 07:07 UTC, MilenIvanovv approved these changes
LGTM

2021-09-10 07:14 UTC, merged